// [CO2: ES6 Modules / Modular Design] - Importing components and dependencies
import { useState, useEffect } from "react";
import CardIcon from "../ui/CardIcon.jsx";
import MapView from "../modules/MapView.jsx";
import { AIRLINES } from "../../data/airlines.js";
import { CURRENCIES } from "../../data/currencies.js";
import { detectCurrency, formatMoney, fmtDate, fmtShort, flightPrice, flightDur, layoverH } from "../../utils/helpers.js";

const S = {
  gc: (delay=0,extra={}) => ({background:"rgba(255,255,255,0.84)",backdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.9)",borderRadius:22,boxShadow:"0 8px 40px rgba(255,100,0,0.09),0 2px 8px rgba(0,0,0,0.04)",padding:26,position:"relative",overflow:"hidden",animationDelay:`${delay}ms`,...extra}),
};

// [CO4: State Management Strategies] - Persistence layer utilizing localStorage to maintain data across browser instances
const LS_KEY = "tripforge_saved_trips";
const LB_KEY = "tripforge_bookings";
function loadSavedTrips(){ try{ return JSON.parse(localStorage.getItem(LS_KEY))||[]; }catch{ return []; } }
function persistTrips(arr){ localStorage.setItem(LS_KEY, JSON.stringify(arr)); }
function loadBookings(){ try{ return JSON.parse(localStorage.getItem(LB_KEY))||[]; }catch{ return []; } }
function persistBookings(arr){ localStorage.setItem(LB_KEY, JSON.stringify(arr)); }

// [CO2: Async Pipelines & Functional Composition] - Dynamic importing of external PDF bundlers
async function generatePDF({ allStops, legs, dateStart, dateEnd, nights, passengers, payingPax, totalPax, totalCostUSD, taxUSD, insUSD, currency, fm, selAirlineName }){
  // [CO5: Rendering Optimizations] - Code splitting / Lazy-loading jsPDF libraries to minimize bundle sizes
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit:"mm", format:"a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 18;
  const line = (lbl,val,bold=false) => {
    doc.setFont("helvetica", bold?"bold":"normal");
    doc.setFontSize(11);
    doc.text(lbl, 18, y);
    doc.text(val, W-18, y, {align:"right"});
    y += 7;
  };

  // Header bar
  doc.setFillColor(255,140,0);
  doc.rect(0,0,W,36,"F");
  doc.setTextColor(255,255,255);
  doc.setFont("helvetica","bold"); doc.setFontSize(22);
  doc.text("TripForge", 18, 16);
  doc.setFontSize(10); doc.setFont("helvetica","normal");
  doc.text("Your Complete Itinerary", 18, 24);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, W-18, 24, {align:"right"});
  y = 46;

  // Trip overview
  doc.setTextColor(15,23,42);
  doc.setFont("helvetica","bold"); doc.setFontSize(14);
  doc.text("Trip Overview", 18, y); y+=9;
  doc.setDrawColor(255,140,0); doc.setLineWidth(0.5); doc.line(18,y,W-18,y); y+=7;

  line("Route:", allStops.map(s=>`${s.code}`).join(" → "));
  line("Dates:", `${fmtDate(dateStart)} – ${fmtDate(dateEnd)}`);
  line("Duration:", `${nights} nights`);
  line("Passengers:", `${passengers.adults} adult${passengers.adults!==1?"s":""}, ${passengers.children} child${passengers.children!==1?"ren":""}, ${passengers.infants} infant${passengers.infants!==1?"s":""}`);
  line("Currency:", `${currency.code} (${currency.sym})`);
  line("Airline:", selAirlineName);
  y += 5;

  // Flight legs
  doc.setFont("helvetica","bold"); doc.setFontSize(14);
  doc.text("Flight Legs", 18, y); y+=9;
  doc.setDrawColor(255,140,0); doc.line(18,y,W-18,y); y+=7;
  legs.forEach(l => {
    line(`✈  ${l.label}`, `${fm(l.usd)} /pax  ·  ${fm(l.usd*payingPax)} total`);
  });
  y += 3;

  // Cost breakdown
  doc.setFont("helvetica","bold"); doc.setFontSize(14);
  doc.text("Cost Breakdown", 18, y); y+=9;
  doc.setDrawColor(255,140,0); doc.line(18,y,W-18,y); y+=7;
  legs.forEach(l => line(l.label, fm(l.usd*payingPax)));
  line("Taxes & Fees", fm(taxUSD*payingPax));
  line("Travel Insurance", fm(insUSD*payingPax));
  y += 2;
  doc.setDrawColor(255,140,0); doc.line(18,y,W-18,y); y+=7;
  line("Grand Total (est.)", fm(totalCostUSD), true);
  y += 5;

  // Visa info
  doc.setFont("helvetica","bold"); doc.setFontSize(14);
  doc.text("Visa Information", 18, y); y+=9;
  doc.setDrawColor(255,140,0); doc.line(18,y,W-18,y); y+=7;
  allStops.forEach(s => {
    line(`${s.name} (${s.code})`, `${s.visa} — ${s.visaBadge}`);
  });

  // Footer
  y = doc.internal.pageSize.getHeight() - 14;
  doc.setFontSize(9); doc.setTextColor(148,163,184);
  doc.text("Generated by TripForge · tripforge.app", W/2, y, {align:"center"});

  doc.save(`TripForge_Itinerary_${new Date().toISOString().slice(0,10)}.pdf`);
}

/* ─── Email builder ─── */
function buildMailto({ allStops, legs, dateStart, dateEnd, nights, totalPax, payingPax, totalCostUSD, fm, selAirlineName }){
  const route = allStops.map(s=>s.code).join(" → ");
  const subject = encodeURIComponent(`TripForge Itinerary: ${route}`);
  const body = [
    `✈ TripForge Itinerary`,
    ``,
    `Route: ${route}`,
    `Dates: ${fmtDate(dateStart)} – ${fmtDate(dateEnd)} (${nights} nights)`,
    `Passengers: ${totalPax}`,
    `Airline: ${selAirlineName}`,
    ``,
    `--- Flight Legs ---`,
    ...legs.map(l=>`  ${l.label}: ${fm(l.usd*payingPax)}`),
    ``,
    `Grand Total (est.): ${fm(totalCostUSD)}`,
    ``,
    `Plan your trip at tripforge.app`,
  ].join("\n");
  return `mailto:?subject=${subject}&body=${encodeURIComponent(body)}`;
}

/* ─── Share text builder ─── */
function shareText({ allStops, dateStart, dateEnd, nights, totalPax, totalCostUSD, fm }){
  const route = allStops.map(s=>s.code).join(" → ");
  return `✈ Check out my TripForge itinerary!\n\n${route}\n${fmtDate(dateStart)} – ${fmtDate(dateEnd)} · ${nights} nights · ${totalPax} pax\nEstimated: ${fm(totalCostUSD)}\n\nPlan yours at tripforge.app`;
}

/* ─── Booking Modal Component ─── */
function BookingModal({ show, onClose, allStops, legs, dateStart, dateEnd, nights, passengers, payingPax, totalPax, totalCostUSD, fm, selAirline, showToast }){
  const [paxNames, setPaxNames] = useState(Array(payingPax).fill(""));
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [payMethod, setPayMethod] = useState("card");
  const [confirmed, setConfirmed] = useState(false);
  const [bookingRef, setBookingRef] = useState("");
  const [errors, setErrors] = useState({});

  // Reset when modal opens
  useEffect(()=>{
    if(show){
      setPaxNames(Array(payingPax).fill(""));
      setEmail(""); setPhone(""); setPayMethod("card");
      setConfirmed(false); setBookingRef(""); setErrors({});
    }
  },[show, payingPax]);

  if(!show) return null;

  function validate(){
    const errs = {};
    paxNames.forEach((n,i)=>{ if(!n.trim()) errs[`pax${i}`]="Required"; });
    if(!email.trim()||!email.includes("@")) errs.email="Valid email required";
    if(!phone.trim()||phone.length<6) errs.phone="Valid phone required";
    setErrors(errs);
    return Object.keys(errs).length===0;
  }

  function handleConfirm(){
    if(!validate()) return;
    const ref = "TF-"+Math.random().toString(36).substring(2,8).toUpperCase();
    setBookingRef(ref);
    setConfirmed(true);
    // Save booking to localStorage
    const booking = {
      id: Date.now(),
      ref,
      route: allStops.map(s=>s.code).join(" → "),
      airline: selAirline.name,
      dates: `${fmtDate(dateStart)} – ${fmtDate(dateEnd)}`,
      passengers: totalPax,
      total: fm(totalCostUSD),
      paxNames: paxNames.filter(n=>n.trim()),
      email, phone, payMethod,
      bookedAt: new Date().toISOString(),
    };
    const bookings = loadBookings();
    bookings.unshift(booking);
    persistBookings(bookings);
    showToast(`🎉 Booking confirmed: ${ref}`,"🎉");
  }

  const overlay = {position:"fixed",inset:0,zIndex:9999,background:"rgba(0,0,0,0.45)",backdropFilter:"blur(6px)",display:"flex",alignItems:"center",justifyContent:"center",padding:20};
  const modal = {background:"#fff",borderRadius:24,maxWidth:540,width:"100%",maxHeight:"90vh",overflowY:"auto",boxShadow:"0 24px 80px rgba(0,0,0,0.18)",position:"relative"};
  const inputStyle = (err) => ({width:"100%",padding:"11px 14px",borderRadius:11,border:`1.5px solid ${err?"#ef4444":"rgba(255,140,0,0.2)"}`,background:"#fff",fontSize:13,fontFamily:"inherit",outline:"none",transition:"border 0.2s",boxSizing:"border-box"});

  if(confirmed){
    return (
      <div style={overlay} onClick={onClose}>
        <div style={{...modal, padding:40, textAlign:"center"}} onClick={e=>e.stopPropagation()}>
          <div style={{width:72,height:72,borderRadius:"50%",background:"linear-gradient(135deg,#22c55e,#16a34a)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:34,margin:"0 auto 18px",boxShadow:"0 8px 30px rgba(34,197,94,0.35)"}}>✓</div>
          <div style={{fontSize:24,fontWeight:800,letterSpacing:"-0.03em",marginBottom:6}}>Booking Confirmed!</div>
          <div style={{fontSize:13,color:"#475569",marginBottom:18}}>Your tickets have been booked successfully.</div>
          <div style={{background:"rgba(255,140,0,0.06)",border:"1px solid rgba(255,140,0,0.15)",borderRadius:14,padding:"16px 20px",marginBottom:18}}>
            <div style={{fontSize:11,fontWeight:600,color:"#94A3B8",marginBottom:4}}>Booking Reference</div>
            <div style={{fontSize:28,fontWeight:800,color:"#FF8C00",letterSpacing:"0.05em"}}>{bookingRef}</div>
          </div>
          <div style={{fontSize:12,color:"#475569",marginBottom:4}}>
            <strong>Route:</strong> {allStops.map(s=>s.code).join(" → ")}
          </div>
          <div style={{fontSize:12,color:"#475569",marginBottom:4}}>
            <strong>Airline:</strong> {selAirline.name}
          </div>
          <div style={{fontSize:12,color:"#475569",marginBottom:4}}>
            <strong>Total:</strong> {fm(totalCostUSD)}
          </div>
          <div style={{fontSize:12,color:"#475569",marginBottom:18}}>
            <strong>Passengers:</strong> {totalPax}
          </div>
          <div style={{fontSize:10,color:"#94A3B8",marginBottom:18}}>A confirmation email has been sent to {email}</div>
          <button onClick={onClose} style={{padding:"12px 32px",borderRadius:12,border:"none",background:"linear-gradient(135deg,#FF8C00,#FF4500)",color:"#fff",fontSize:14,fontWeight:700,cursor:"pointer",boxShadow:"0 6px 22px rgba(255,140,0,0.35)",fontFamily:"inherit"}}>Done</button>
        </div>
      </div>
    );
  }

  return (
    <div style={overlay} onClick={onClose}>
      <div style={modal} onClick={e=>e.stopPropagation()}>
        {/* Header */}
        <div style={{background:"linear-gradient(135deg,#FF8C00,#FF4500)",borderRadius:"24px 24px 0 0",padding:"22px 28px",position:"relative"}}>
          <button onClick={onClose} style={{position:"absolute",top:14,right:18,width:32,height:32,borderRadius:10,border:"none",background:"rgba(255,255,255,0.2)",color:"#fff",fontSize:16,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>✕</button>
          <div style={{fontSize:18,fontWeight:800,color:"#fff",letterSpacing:"-0.02em"}}>🎫 Book Tickets</div>
          <div style={{fontSize:12,color:"rgba(255,255,255,0.8)",marginTop:4}}>{allStops.map(s=>s.code).join(" → ")} · {selAirline.name}</div>
        </div>

        <div style={{padding:"24px 28px"}}>
          {/* Booking summary */}
          <div style={{background:"rgba(255,140,0,0.04)",border:"1px solid rgba(255,140,0,0.12)",borderRadius:14,padding:"14px 18px",marginBottom:20}}>
            <div style={{display:"flex",justifyContent:"space-between",fontSize:12,marginBottom:6}}>
              <span style={{color:"#475569"}}>Dates</span>
              <span style={{fontWeight:700}}>{fmtDate(dateStart)} – {fmtDate(dateEnd)}</span>
            </div>
            <div style={{display:"flex",justifyContent:"space-between",fontSize:12,marginBottom:6}}>
              <span style={{color:"#475569"}}>Passengers</span>
              <span style={{fontWeight:700}}>{totalPax} ({passengers.adults}A + {passengers.children}C + {passengers.infants}I)</span>
            </div>
            <div style={{display:"flex",justifyContent:"space-between",fontSize:12,marginBottom:6}}>
              <span style={{color:"#475569"}}>Airline</span>
              <span style={{fontWeight:700}}>{selAirline.name} ({selAirline.code})</span>
            </div>
            <div style={{display:"flex",justifyContent:"space-between",fontSize:14,fontWeight:800,paddingTop:8,borderTop:"1px dashed rgba(255,140,0,0.2)"}}>
              <span>Total</span>
              <span style={{color:"#FF8C00"}}>{fm(totalCostUSD)}</span>
            </div>
          </div>

          {/* Passenger names */}
          <div style={{fontSize:13,fontWeight:700,marginBottom:10}}>👥 Passenger Details</div>
          {paxNames.map((name,i)=>(
            <div key={i} style={{marginBottom:10}}>
              <label style={{fontSize:11,fontWeight:600,color:"#475569",marginBottom:4,display:"block"}}>Passenger {i+1} {i<passengers.adults?"(Adult)":i<passengers.adults+passengers.children?"(Child)":"(Infant)"}</label>
              <input value={name} onChange={e=>{const arr=[...paxNames];arr[i]=e.target.value;setPaxNames(arr);}}
                placeholder="Full name as on passport"
                style={inputStyle(errors[`pax${i}`])} />
              {errors[`pax${i}`]&&<div style={{fontSize:10,color:"#ef4444",marginTop:3}}>{errors[`pax${i}`]}</div>}
            </div>
          ))}

          {/* Contact info */}
          <div style={{fontSize:13,fontWeight:700,marginBottom:10,marginTop:16}}>📧 Contact Information</div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:16}}>
            <div>
              <label style={{fontSize:11,fontWeight:600,color:"#475569",marginBottom:4,display:"block"}}>Email</label>
              <input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@email.com" style={inputStyle(errors.email)} />
              {errors.email&&<div style={{fontSize:10,color:"#ef4444",marginTop:3}}>{errors.email}</div>}
            </div>
            <div>
              <label style={{fontSize:11,fontWeight:600,color:"#475569",marginBottom:4,display:"block"}}>Phone</label>
              <input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+1 234 567 890" style={inputStyle(errors.phone)} />
              {errors.phone&&<div style={{fontSize:10,color:"#ef4444",marginTop:3}}>{errors.phone}</div>}
            </div>
          </div>

          {/* Payment method */}
          <div style={{fontSize:13,fontWeight:700,marginBottom:10}}>💳 Payment Method</div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,marginBottom:24}}>
            {[["card","💳","Credit Card"],["paypal","🅿️","PayPal"],["upi","📱","UPI"]].map(([val,ico,lbl])=>(
              <div key={val} onClick={()=>setPayMethod(val)}
                style={{padding:"14px 12px",borderRadius:13,border:`1.5px solid ${payMethod===val?"#FF8C00":"rgba(255,140,0,0.12)"}`,background:payMethod===val?"rgba(255,140,0,0.04)":"#fff",cursor:"pointer",textAlign:"center",transition:"all 0.2s",boxShadow:payMethod===val?"0 0 0 3px rgba(255,140,0,0.1)":"none"}}>
                <div style={{fontSize:22,marginBottom:4}}>{ico}</div>
                <div style={{fontSize:11,fontWeight:700,color:payMethod===val?"#FF8C00":"#475569"}}>{lbl}</div>
              </div>
            ))}
          </div>

          {/* Simulated notice */}
          <div style={{background:"rgba(59,130,246,0.06)",border:"1px solid rgba(59,130,246,0.15)",borderRadius:10,padding:"10px 14px",marginBottom:18,display:"flex",alignItems:"center",gap:8}}>
            <span style={{fontSize:16}}>ℹ️</span>
            <span style={{fontSize:11,color:"#475569"}}>This is a demo booking. No real payment will be charged.</span>
          </div>

          {/* Confirm button */}
          <button onClick={handleConfirm}
            style={{width:"100%",padding:"14px 20px",borderRadius:13,border:"none",background:"linear-gradient(135deg,#FF8C00,#FF4500)",color:"#fff",fontSize:15,fontWeight:800,cursor:"pointer",boxShadow:"0 8px 28px rgba(255,140,0,0.35)",fontFamily:"inherit",letterSpacing:"-0.01em"}}>
            🎫 Confirm Booking · {fm(totalCostUSD)}
          </button>
        </div>
      </div>
    </div>
  );
}


export default function Step3({ tripSrc, tripDst, stops, dateStart, dateEnd, passengers, currency, onCurrencyChange, onPaxChange, onBack, showToast, onSaveTrip, onLoadTrip, bookingTrigger }) {
  const [selAirline, setSelAirline] = useState(0);
  const [savedTrips, setSavedTrips] = useState(loadSavedTrips());
  const [showBooking, setShowBooking] = useState(false);

  // Open booking modal when header "Book Now" is clicked
  useEffect(() => {
    if (bookingTrigger > 0) setShowBooking(true);
  }, [bookingTrigger]);

  const allStops = [tripSrc, ...stops, tripDst];
  const payingPax = passengers.adults+passengers.children;
  const totalPax = passengers.adults+passengers.children+passengers.infants;
  const nights = dateStart&&dateEnd ? Math.round((dateEnd-dateStart)/86400000) : 0;

  function getStopDate(i,total){
    if(!dateStart||!dateEnd||total<2) return null;
    const d=new Date(dateStart.getTime()+i*(dateEnd-dateStart)/(total-1));
    return fmtShort(d);
  }

  const airlineMul = 0.93 + selAirline * 0.065;
  const legs = allStops.slice(1).map((s,i)=>{
    const rawUSD = flightPrice(allStops[i],s);
    const usd = Math.round((rawUSD * airlineMul)/10)*10;
    return {label:`${allStops[i].flag}${allStops[i].code}→${s.flag}${s.code}`, usd};
  });
  const taxUSD = Math.round(legs.reduce((s,l)=>s+l.usd,0)*0.12);
  const insUSD = nights*6;
  const allCostItems = [...legs,{label:"Taxes & Fees",usd:taxUSD},{label:"Travel Insurance",usd:insUSD}];
  const totalCostUSD = allCostItems.reduce((s,i)=>s+i.usd*payingPax,0);
  const maxMul = 0.93 + (AIRLINES.length - 1) * 0.065;
  const maxLegs = allStops.slice(1).map((s,i)=>{
    const rawUSD = flightPrice(allStops[i],s);
    return Math.round((rawUSD * maxMul)/10)*10;
  });
  const maxTaxUSD = Math.round(maxLegs.reduce((sum,val)=>sum+val,0)*0.12);
  const maxInsUSD = nights*6;
  const maxItemUSD = Math.max(...maxLegs, maxTaxUSD, maxInsUSD, 1) * payingPax;
  const baseUSD = legs.reduce((s,l)=>s+l.usd,0);
  const totalDur = allStops.slice(1).reduce((s,c,i)=>s+flightDur(allStops[i],c),0);

  const autoCurr = detectCurrency(tripSrc.country, CURRENCIES);
  const dstCurr = detectCurrency(tripDst.country, CURRENCIES);
  const chipSet = new Map();
  [autoCurr,dstCurr,...CURRENCIES.slice(0,3)].forEach(c=>chipSet.set(c.code,c));
  const chips = [...chipSet.values()].slice(0,5);
  const fm = (usd) => formatMoney(usd, currency);

  /* ─── Save Trip ─── */
  function handleSaveTrip(){
    const trip = {
      id: Date.now(),
      name: `${tripSrc.code} → ${tripDst.code}`,
      route: allStops.map(s=>s.code).join(" → "),
      meta: `${allStops.length} cities · ${nights} nights`,
      price: fm(totalCostUSD),
      date: new Date().toLocaleDateString("en-US",{month:"short",year:"numeric"}),
      icon: ["🌏","🏰","🦘","✈️","🗺️","🌴","🏔️","🎌"][Math.floor(Math.random()*8)],
      // Serialise trip data for loading
      data: {
        srcCode: tripSrc.code,
        dstCode: tripDst.code,
        stopCodes: stops.map(s=>s.code),
        dateStart: dateStart?.toISOString(),
        dateEnd: dateEnd?.toISOString(),
        passengers,
        currencyCode: currency.code,
        selAirline,
      },
    };
    const trips = loadSavedTrips();
    trips.unshift(trip);
    persistTrips(trips);
    setSavedTrips(trips);
    showToast("💾 Trip saved!","💾");
    if(onSaveTrip) onSaveTrip(trip);
  }

  function handleDeleteTrip(id){
    const trips = loadSavedTrips().filter(t=>t.id!==id);
    persistTrips(trips);
    setSavedTrips(trips);
    showToast("🗑 Trip removed","🗑️");
  }

  function handleLoadTrip(trip){
    if(onLoadTrip) onLoadTrip(trip.data);
    showToast(`🗺️ Loaded: ${trip.name}`,"🗺️");
  }

  /* ─── Export PDF ─── */
  async function handleExportPDF(){
    try {
      await generatePDF({
        allStops, legs, dateStart, dateEnd, nights, passengers,
        payingPax, totalPax, totalCostUSD, taxUSD, insUSD,
        currency, fm, selAirlineName: AIRLINES[selAirline].name,
      });
      showToast("📄 PDF downloaded!","📄");
    } catch(e){
      console.error("PDF generation failed:", e);
      showToast("❌ PDF generation failed","❌");
    }
  }

  /* ─── Email ─── */
  function handleEmail(){
    const url = buildMailto({
      allStops, legs, dateStart, dateEnd, nights, totalPax, payingPax,
      totalCostUSD, fm, selAirlineName: AIRLINES[selAirline].name,
    });
    window.open(url, "_blank");
    showToast("📧 Opening email client…","📧");
  }

  /* ─── Share helpers ─── */
  function getShareTxt(){
    return shareText({ allStops, dateStart, dateEnd, nights, totalPax, totalCostUSD, fm });
  }

  function handleCopyLink(){
    const txt = getShareTxt();
    navigator.clipboard.writeText(txt).then(()=>{
      showToast("📋 Copied to clipboard!","📋");
    }).catch(()=>{
      // Fallback
      const ta = document.createElement("textarea");
      ta.value = txt; document.body.appendChild(ta);
      ta.select(); document.execCommand("copy");
      document.body.removeChild(ta);
      showToast("📋 Copied to clipboard!","📋");
    });
  }

  function handleShareSocial(platform){
    const txt = encodeURIComponent(getShareTxt());
    const urls = {
      WhatsApp: `https://wa.me/?text=${txt}`,
      Twitter: `https://twitter.com/intent/tweet?text=${txt}`,
      Facebook: `https://www.facebook.com/sharer/sharer.php?quote=${txt}`,
      Email: buildMailto({ allStops, legs, dateStart, dateEnd, nights, totalPax, payingPax, totalCostUSD, fm, selAirlineName: AIRLINES[selAirline].name }),
    };
    window.open(urls[platform], "_blank");
    showToast(`${platform === "WhatsApp"?"💬":platform==="Twitter"?"🐦":platform==="Facebook"?"📘":"📧"} Opening ${platform}…`, "🔗");
  }

  function handleNativeShare(){
    if(navigator.share){
      navigator.share({
        title: `TripForge: ${allStops.map(s=>s.code).join(" → ")}`,
        text: getShareTxt(),
      }).catch(()=>{});
    }
  }

  /* ─── Layover Module ─── */
  const LayoverModule = () => (
    <div>
      <CardIcon icon="⏱️"/>
      <div style={{fontSize:15,fontWeight:800,letterSpacing:"-0.025em",marginBottom:4}}>Layover Display</div>
      <div style={{fontSize:12.5,color:"#475569",marginBottom:14}}>Timeline of your journey with connection wait times.</div>
      <div style={{display:"flex",alignItems:"flex-start",overflowX:"auto",paddingBottom:10}}>
        {allStops.map((stop,i)=>(
          <div key={stop.code} style={{display:"flex",alignItems:"flex-start"}}>
            <div style={{textAlign:"center",minWidth:80,flexShrink:0}}>
              <div style={{width:14,height:14,borderRadius:"50%",background:"linear-gradient(135deg,#FF8C00,#FF4500)",margin:"0 auto 7px",boxShadow:"0 0 0 4px rgba(255,140,0,0.13)"}}/>
              <div style={{fontSize:12,fontWeight:800}}>{stop.flag}{stop.code}</div>
              <div style={{fontSize:10,color:"#94A3B8",marginTop:3}}>{getStopDate(i,allStops.length)}</div>
            </div>
            {i<allStops.length-1&&(()=>{
              const wh=layoverH(i),wCls=wh<1.5?"tight":wh>4?"long":"ok";
              const colors={ok:"rgba(34,197,94,0.1)",long:"rgba(255,140,0,0.1)",tight:"rgba(239,68,68,0.08)"};
              const tcols={ok:"#16a34a",long:"#FF8C00",tight:"#ef4444"};
              const borders={ok:"rgba(34,197,94,0.2)",long:"rgba(255,140,0,0.22)",tight:"rgba(239,68,68,0.25)"};
              const d=flightDur(allStops[i],allStops[i+1]);
              return (
                <div style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:5,minWidth:90,paddingTop:2}}>
                  <div style={{width:"100%",height:2,background:"repeating-linear-gradient(90deg,#FF8C00 0,#FF8C00 6px,transparent 6px,transparent 12px)"}}/>
                  <div style={{fontSize:10,fontWeight:700,padding:"3px 10px",borderRadius:6,whiteSpace:"nowrap",background:colors[wCls],color:tcols[wCls],border:`1px solid ${borders[wCls]}`}}>{wh.toFixed(1)}h {wh<1.5?"⚠":"layover"}</div>
                  <div style={{fontSize:10,color:"#94A3B8"}}>~{d}h flight</div>
                </div>
              );
            })()}
          </div>
        ))}
      </div>
      <div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:4}}>
        {[["rgba(34,197,94,0.55)","Comfortable (>2h)"],["rgba(255,140,0,0.55)","Long layover (>4h)"],["rgba(239,68,68,0.55)","Tight (<1.5h)"]].map(([bg,lbl])=>(
          <div key={lbl} style={{display:"flex",alignItems:"center",gap:5,fontSize:11,color:"#475569"}}>
            <div style={{width:8,height:8,borderRadius:2,background:bg}}/>{lbl}
          </div>
        ))}
      </div>
    </div>
  );

  return (
    <div style={{maxWidth:1180,margin:"0 auto",padding:"44px 40px"}}>
      <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",flexWrap:"wrap",gap:12,marginBottom:32}}>
        <div>
          <span style={{display:"inline-flex",alignItems:"center",gap:6,background:"rgba(255,140,0,0.08)",border:"1px solid rgba(255,140,0,0.18)",padding:"5px 14px",borderRadius:99,fontSize:11,fontWeight:700,color:"#FF8C00",textTransform:"uppercase",letterSpacing:"0.07em",marginBottom:12}}>
            <span style={{width:5,height:5,borderRadius:"50%",background:"#FF8C00",display:"inline-block"}}/>Step 3 of 3
          </span>
          <h2 style={{fontSize:32,fontWeight:800,letterSpacing:"-0.03em",color:"#0F172A",lineHeight:1.12}}>Your <span style={{background:"linear-gradient(135deg,#FF8C00,#FF4500)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>Complete Itinerary</span></h2>
          <p style={{fontSize:14,color:"#475569",marginTop:8}}>All modules update live based on your selected cities and dates.</p>
        </div>
        <button onClick={onBack} style={{padding:"9px 18px",borderRadius:10,border:"1.5px solid rgba(255,140,0,0.28)",background:"transparent",color:"#FF8C00",fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>← Edit Route</button>
      </div>

      {/* PASSENGERS BAR */}
      <div style={{background:"rgba(255,255,255,0.95)",border:"1px solid rgba(255,140,0,0.14)",borderRadius:17,padding:"16px 22px",boxShadow:"0 4px 20px rgba(255,100,0,0.07)",display:"flex",alignItems:"center",gap:16,flexWrap:"wrap",marginBottom:16}}>
        <span style={{fontSize:12,fontWeight:700,color:"#475569",flexShrink:0}}>👥 Passengers</span>
        <div style={{display:"flex",gap:10,flex:1,flexWrap:"wrap"}}>
          {[{key:"adults",icon:"🧑",label:"Adults",sub:"12+ yrs",min:1},{key:"children",icon:"👦",label:"Children",sub:"2–11 yrs",min:0},{key:"infants",icon:"👶",label:"Infants",sub:"Under 2",min:0}].map(p=>(
            <div key={p.key} style={{display:"flex",alignItems:"center",gap:9,background:"#fff",border:"1px solid rgba(255,140,0,0.16)",borderRadius:12,padding:"8px 14px"}}>
              <div><div style={{fontSize:12,fontWeight:700,color:"#0F172A"}}>{p.icon} {p.label}</div><div style={{fontSize:10,color:"#94A3B8",marginTop:1}}>{p.sub}</div></div>
              <div style={{display:"flex",alignItems:"center",gap:8,marginLeft:6}}>
                <button onClick={()=>onPaxChange(p.key,Math.max(p.min,passengers[p.key]-1))} disabled={passengers[p.key]<=p.min}
                  style={{width:28,height:28,borderRadius:8,border:"1.5px solid rgba(255,140,0,0.25)",background:"transparent",color:"#FF8C00",fontSize:16,fontWeight:700,cursor:passengers[p.key]<=p.min?"not-allowed":"pointer",opacity:passengers[p.key]<=p.min?0.28:1,fontFamily:"inherit"}}>−</button>
                <span style={{fontSize:16,fontWeight:800,minWidth:20,textAlign:"center"}}>{passengers[p.key]}</span>
                <button onClick={()=>onPaxChange(p.key,Math.min(9,passengers[p.key]+1))}
                  style={{width:28,height:28,borderRadius:8,border:"1.5px solid rgba(255,140,0,0.25)",background:"transparent",color:"#FF8C00",fontSize:16,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>+</button>
              </div>
            </div>
          ))}
        </div>
        <div style={{marginLeft:"auto",display:"flex",alignItems:"center",gap:7,background:"linear-gradient(135deg,#FF8C00,#FF4500)",color:"#fff",padding:"8px 18px",borderRadius:10,fontSize:12,fontWeight:700,boxShadow:"0 3px 12px rgba(255,140,0,0.28)",whiteSpace:"nowrap",flexShrink:0}}>
        🧳 {totalPax} passenger{totalPax!==1?"s":""}
        </div>
      </div>

      {/* CURRENCY BAR */}
      <div style={{background:"rgba(255,255,255,0.95)",border:"1px solid rgba(255,140,0,0.14)",borderRadius:17,padding:"14px 22px",boxShadow:"0 4px 20px rgba(255,100,0,0.07)",display:"flex",alignItems:"center",gap:14,flexWrap:"wrap",marginBottom:22}}>
        <span style={{fontSize:12,fontWeight:700,color:"#475569",flexShrink:0}}>💱 Currency</span>
        <div style={{display:"flex",gap:8,flexWrap:"wrap",flex:1}}>
          {chips.map(c=>(
            <div key={c.code} onClick={()=>onCurrencyChange(c.code,true)}
              style={{display:"flex",alignItems:"center",gap:6,padding:"7px 14px",borderRadius:10,fontSize:12.5,fontWeight:700,cursor:"pointer",border:c.code===currency.code?"none":"1.5px solid rgba(255,140,0,0.14)",background:c.code===currency.code?"linear-gradient(135deg,#FF8C00,#FF4500)":"#fff",color:c.code===currency.code?"#fff":"#475569",boxShadow:c.code===currency.code?"0 3px 14px rgba(255,140,0,0.35)":"none",transition:"all 0.18s",whiteSpace:"nowrap"}}>
              <span>{c.flag}</span><span style={{fontSize:15,fontWeight:800}}>{c.sym}</span><span style={{fontSize:11}}>{c.code}</span>
            </div>
          ))}
        </div>
        <select value={currency.code} onChange={e=>onCurrencyChange(e.target.value,true)}
          style={{padding:"7px 12px",borderRadius:10,border:"1.5px solid rgba(255,140,0,0.2)",background:"#fff",fontSize:12,fontWeight:600,color:"#0F172A",fontFamily:"inherit",outline:"none",cursor:"pointer"}}>
          <option value="">More currencies…</option>
          {CURRENCIES.map(c=><option key={c.code} value={c.code}>{c.flag} {c.code} — {c.name}</option>)}
        </select>
      </div>

      {/* MODULES GRID */}
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:20,alignItems:"stretch"}}>
        <div style={{...S.gc(0),gridColumn:"1/3"}}><LayoverModule/></div>
        <div style={S.gc(80)}>
          <CardIcon icon="💰"/>
          <div style={{fontSize:15,fontWeight:800,letterSpacing:"-0.025em",marginBottom:4}}>Cost Summary</div>
          <div style={{fontSize:12.5,color:"#475569",marginBottom:14}}>Live cost per leg × passengers in your currency.</div>
          {allCostItems.map(item=>{
            const tot=item.usd*payingPax, pct=Math.round(tot/maxItemUSD*100);
            return (
              <div key={item.label} style={{display:"flex",alignItems:"center",gap:10,marginBottom:10}}>
                <div style={{fontSize:12,fontWeight:600,minWidth:110,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{item.label}</div>
                <div style={{flex:1,height:7,background:"rgba(255,140,0,0.09)",borderRadius:99,overflow:"hidden"}}>
                  <div style={{height:"100%",width:`${pct}%`,borderRadius:99,background:"linear-gradient(90deg,#FF8C00,#FF4500)",transition:"width 1.2s cubic-bezier(0.22,1,0.36,1)"}}/>
                </div>
                <div style={{textAlign:"right",minWidth:60}}>
                  <div style={{fontSize:12,fontWeight:700,color:"#FF8C00"}}>{fm(tot)}</div>
                  {payingPax>1&&<div style={{fontSize:9.5,color:"#94A3B8"}}>{fm(item.usd)}/pax</div>}
                </div>
              </div>
            );
          })}
          <div style={{background:"linear-gradient(135deg,#FF8C00,#FF4500)",borderRadius:13,padding:"16px 20px",marginTop:16,display:"flex",justifyContent:"space-between",alignItems:"center",boxShadow:"0 6px 20px rgba(255,140,0,0.28)"}}>
            <div><div style={{fontSize:12,fontWeight:700,color:"rgba(255,255,255,0.82)"}}>Grand Total (est.)</div><div style={{fontSize:10,color:"rgba(255,255,255,0.65)",marginTop:2}}>All taxes included</div></div>
            <div style={{fontSize:26,fontWeight:800,color:"#fff",letterSpacing:"-0.03em"}}>{fm(totalCostUSD)}</div>
          </div>
        </div>

        <div style={S.gc(120)}>
          <CardIcon icon="🛂"/>
          <div style={{fontSize:15,fontWeight:800,letterSpacing:"-0.025em",marginBottom:4}}>Visa Info Panel</div>
          <div style={{fontSize:12.5,color:"#475569",marginBottom:14}}>Requirements for each destination.</div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:9}}>
            {allStops.map(s=>(
              <div key={s.code} style={{display:"flex",alignItems:"center",gap:9,padding:"11px 13px",borderRadius:12,border:`1.5px solid ${s.visaType==="ok"?"rgba(34,197,94,0.18)":"rgba(255,140,0,0.18)"}`,background:s.visaType==="ok"?"rgba(34,197,94,0.055)":"rgba(255,140,0,0.055)"}}>
                <span style={{fontSize:19}}>{s.flag}</span>
                <div style={{flex:1,minWidth:0}}>
                  <div style={{fontSize:11,fontWeight:800,color:"#0F172A",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{s.name}</div>
                  <div style={{fontSize:10,fontWeight:600,marginTop:1,color:s.visaType==="ok"?"#16a34a":"#FF8C00"}}>{s.visa}</div>
                </div>
                <span style={{fontSize:9,fontWeight:700,padding:"2px 6px",borderRadius:5,background:s.visaType==="ok"?"rgba(34,197,94,0.1)":"rgba(255,140,0,0.1)",color:s.visaType==="ok"?"#16a34a":"#FF8C00",flexShrink:0}}>{s.visaBadge}</span>
              </div>
            ))}
          </div>
        </div>
        <div style={{...S.gc(160),gridColumn:"2/4"}}>
          <CardIcon icon="✈️"/>
          <div style={{fontSize:15,fontWeight:800,letterSpacing:"-0.025em",marginBottom:4}}>Airline Compare</div>
          <div style={{fontSize:12.5,color:"#475569",marginBottom:14}}>Best options for your route. Tap to select.</div>
          {AIRLINES.map((a,i)=>{
            const mul_i = 0.93 + i * 0.065;
            const iLegs = allStops.slice(1).map((_s,j)=>Math.round((flightPrice(allStops[j],allStops[j+1]) * mul_i)/10)*10);
            const iFlightTotal = iLegs.reduce((s,l)=>s+l,0);
            const iTax = Math.round(iFlightTotal*0.12);
            const iIns = nights*6;
            const iPerPax = iFlightTotal + iTax + iIns;
            const iTotalAll = iPerPax * payingPax;
            const isSelected = selAirline===i;
            return (
              <div key={a.code} onClick={()=>{setSelAirline(i);showToast(`✈ ${a.name} selected`,"✈️");}}
                style={{display:"flex",alignItems:"center",gap:11,padding:"12px 15px",borderRadius:12,border:`1.5px solid ${isSelected?"#FF8C00":"rgba(255,140,0,0.1)"}`,background:isSelected?"rgba(255,140,0,0.028)":"#fff",cursor:"pointer",marginBottom:8,boxShadow:isSelected?"0 0 0 2.5px rgba(255,140,0,0.1)":"none",transition:"all 0.2s"}}>
                <div style={{width:36,height:36,borderRadius:9,background:`linear-gradient(135deg,${a.grad})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:800,color:"#fff",flexShrink:0}}>{a.code}</div>
                <div style={{flex:1,minWidth:0}}>
                  <div style={{fontSize:12.5,fontWeight:700}}>{a.name}{a.badge&&<span style={{fontSize:9,fontWeight:700,background:"rgba(255,140,0,0.09)",color:"#FF8C00",padding:"2px 7px",borderRadius:5,marginLeft:6}}>{a.badge}</span>}</div>
                  <div style={{fontSize:10,color:"#94A3B8",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis",maxWidth:200}}>{allStops.map(s=>s.code).join("→")}</div>
                  <div style={{fontSize:10,color:"#f59e0b"}}>{"★".repeat(Math.floor(a.rating))}{a.rating%1?"½":""} {a.rating}</div>
                </div>
                <div style={{textAlign:"right",flexShrink:0}}>
                  <div style={{fontSize:16,fontWeight:800,color:isSelected?"#FF4500":"#FF8C00",letterSpacing:"-0.02em"}}>{fm(iTotalAll)}</div>
                  <div style={{fontSize:10,color:"#94A3B8"}}>~{totalDur}h{payingPax>1?` · ${payingPax} pax`:""}</div>
                  {payingPax>1&&<div style={{fontSize:9.5,color:"#94A3B8"}}>{fm(iPerPax)}/person</div>}
                </div>
              </div>
            );
          })}
        </div>

        <div style={{...S.gc(200),gridColumn:"1/3"}}><MapView allStops={allStops} currency={currency}/></div>
        <div style={S.gc(240)}>
          <CardIcon icon="📄"/>
          <div style={{fontSize:15,fontWeight:800,letterSpacing:"-0.025em",marginBottom:4}}>Trip Export</div>
          <div style={{fontSize:12.5,color:"#475569",marginBottom:14}}>Export PDF or email your itinerary.</div>
          <div style={{background:"linear-gradient(135deg,#fffaf5,#fff8f0)",border:"1px dashed rgba(255,140,0,0.28)",borderRadius:14,padding:"18px 20px",position:"relative",overflow:"hidden"}}>
            <div style={{position:"absolute",left:0,top:0,width:4,height:"100%",background:"linear-gradient(to bottom,#FF8C00,#FF4500)"}}/>
            <div style={{fontSize:14,fontWeight:800,marginBottom:4}}>{allStops.map(s=>s.code).join(" → ")}</div>
            <div style={{fontSize:11.5,color:"#475569",marginBottom:12}}>{fmtDate(dateStart)} – {fmtDate(dateEnd)} · {allStops.length} cities · {nights} nights · {totalPax} pax</div>
            {legs.map(l=>(
              <div key={l.label} style={{display:"flex",justifyContent:"space-between",fontSize:12,marginBottom:5}}>
                <span>✈ {l.label}{payingPax>1?` ×${payingPax}`:""}</span>
                <span style={{fontWeight:700,color:"#FF8C00"}}>{fm(l.usd*payingPax)}</span>
              </div>
            ))}
            <div style={{display:"flex",justifyContent:"space-between",fontSize:12,fontWeight:700,borderTop:"1px dashed rgba(255,140,0,0.2)",paddingTop:8,marginTop:4}}>
              <span>Grand Total</span><span style={{color:"#FF8C00"}}>{fm(totalCostUSD)}</span>
            </div>
          </div>
          <div style={{display:"flex",gap:9,marginTop:13}}>
            <button onClick={handleExportPDF} style={{flex:1,padding:10,borderRadius:9,border:"none",background:"linear-gradient(135deg,#FF8C00,#FF4500)",color:"#fff",fontSize:12.5,fontWeight:700,cursor:"pointer",boxShadow:"0 4px 14px rgba(255,140,0,0.32)",fontFamily:"inherit"}}>⬇ Export PDF</button>
            <button onClick={handleEmail} style={{flex:1,padding:10,borderRadius:9,border:"1.5px solid rgba(255,140,0,0.24)",background:"#fff",color:"#FF8C00",fontSize:12.5,fontWeight:700,cursor:"pointer",fontFamily:"inherit"}}>📧 Email</button>
          </div>
        </div>

        {/* SAVED TRIPS — now reads from localStorage */}
        <div style={S.gc(280)}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:5}}>
            <div><CardIcon icon="💾"/><div style={{fontSize:15,fontWeight:800,letterSpacing:"-0.025em"}}>Saved Trips</div></div>
            <div style={{display:"flex",gap:8,alignItems:"center"}}>
              <span style={{fontSize:10,fontWeight:800,background:"linear-gradient(135deg,#FF8C00,#FF4500)",color:"#fff",padding:"4px 10px",borderRadius:99}}>{savedTrips.length} saved</span>
              <button onClick={handleSaveTrip} style={{fontSize:10,fontWeight:700,padding:"5px 12px",borderRadius:8,border:"none",background:"rgba(255,140,0,0.1)",color:"#FF8C00",cursor:"pointer",fontFamily:"inherit"}}>+ Save Current</button>
            </div>
          </div>
          <div style={{fontSize:12.5,color:"#475569",marginBottom:14}}>Your saved itineraries. Click to load.</div>
          {savedTrips.length===0 ? (
            <div style={{textAlign:"center",padding:"24px 16px",color:"#94A3B8",fontSize:12}}>
              <div style={{fontSize:28,marginBottom:8}}>📭</div>
              No saved trips yet. Click "Save Current" to save this itinerary.
            </div>
          ) : (
            savedTrips.slice(0,5).map(s=>(
              <div key={s.id}
                style={{display:"flex",alignItems:"center",gap:11,padding:"12px 14px",borderRadius:12,border:"1.5px solid rgba(255,140,0,0.09)",background:"#fff",cursor:"pointer",marginBottom:9,transition:"all 0.2s"}}
                onMouseEnter={e=>e.currentTarget.style.borderColor="rgba(255,140,0,0.3)"}
                onMouseLeave={e=>e.currentTarget.style.borderColor="rgba(255,140,0,0.09)"}>
                <div onClick={()=>handleLoadTrip(s)} style={{display:"flex",alignItems:"center",gap:11,flex:1,minWidth:0}}>
                  <div style={{width:38,height:38,borderRadius:9,background:"linear-gradient(135deg,rgba(255,140,0,0.12),rgba(255,69,0,0.07))",display:"flex",alignItems:"center",justifyContent:"center",fontSize:17,flexShrink:0}}>{s.icon}</div>
                  <div style={{minWidth:0}}>
                    <div style={{fontSize:12.5,fontWeight:700,whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{s.name}</div>
                    <div style={{fontSize:10.5,color:"#94A3B8",marginTop:2}}>{s.route} · {s.meta}</div>
                  </div>
                </div>
                <div style={{textAlign:"right",flexShrink:0}}>
                  <div style={{fontSize:14,fontWeight:800,color:"#FF8C00"}}>{s.price}</div>
                  <div style={{fontSize:9,fontWeight:700,padding:"2px 7px",borderRadius:5,background:"rgba(255,140,0,0.07)",color:"#FF8C00",marginTop:4}}>{s.date}</div>
                </div>
                <button onClick={(e)=>{e.stopPropagation();handleDeleteTrip(s.id);}}
                  style={{width:26,height:26,borderRadius:7,border:"1px solid rgba(239,68,68,0.2)",background:"rgba(239,68,68,0.05)",color:"#ef4444",fontSize:12,cursor:"pointer",fontFamily:"inherit",flexShrink:0,display:"flex",alignItems:"center",justifyContent:"center"}}
                  title="Delete trip">✕</button>
              </div>
            ))
          )}
        </div>

        {/* SHARE ITINERARY — now functional */}
        <div style={{...S.gc(320),gridColumn:"2/4"}}>
          <CardIcon icon="🔗"/>
          <div style={{fontSize:15,fontWeight:800,letterSpacing:"-0.025em",marginBottom:4}}>Share Itinerary</div>
          <div style={{fontSize:12.5,color:"#475569",marginBottom:14}}>Share via link, QR code, or social platforms.</div>
          <div style={{display:"flex",gap:13,alignItems:"flex-start",marginBottom:14}}>
            <div style={{width:62,height:62,borderRadius:11,background:"linear-gradient(135deg,rgba(255,140,0,0.08),rgba(255,140,0,0.03))",border:"1px solid rgba(255,140,0,0.18)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:26,flexShrink:0}}>▦</div>
            <div>
              <div style={{fontSize:13,fontWeight:800}}>{allStops.map(s=>s.code).join(" → ")}</div>
              <div style={{fontSize:11,color:"#475569",marginTop:3}}>{tripSrc.name} → {tripDst.name} · {nights} nights</div>
              <div style={{marginTop:8,fontSize:10.5,color:"#94A3B8"}}>📋 Click Copy to share your itinerary</div>
            </div>
          </div>
          <div style={{display:"flex",gap:8,marginBottom:10}}>
            <input readOnly value={getShareTxt().split("\n")[0]} style={{flex:1,padding:"10px 13px",borderRadius:10,border:"1.5px solid rgba(255,140,0,0.18)",background:"#fff",fontSize:11.5,color:"#475569",fontFamily:"inherit",outline:"none"}}/>
            <button onClick={handleCopyLink} style={{padding:"10px 14px",borderRadius:10,border:"none",background:"linear-gradient(135deg,#FF8C00,#FF4500)",color:"#fff",fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:"inherit",boxShadow:"0 4px 14px rgba(255,140,0,0.3)"}}>Copy</button>
          </div>
          <div style={{display:"grid",gridTemplateColumns: typeof navigator !== "undefined" && navigator.share ? "repeat(5,1fr)" : "repeat(4,1fr)",gap:8}}>
            {[["💬","WhatsApp"],["🐦","Twitter"],["📘","Facebook"],["📧","Email"]].map(([ico,lbl])=>(
              <div key={lbl} onClick={()=>handleShareSocial(lbl)}
                style={{padding:"9px 8px",borderRadius:10,border:"1.5px solid rgba(255,140,0,0.11)",background:"#fff",textAlign:"center",fontSize:11,fontWeight:700,cursor:"pointer",transition:"all 0.2s",color:"#0F172A"}}
                onMouseEnter={e=>{e.currentTarget.style.borderColor="#FF8C00";e.currentTarget.style.color="#FF8C00";}}
                onMouseLeave={e=>{e.currentTarget.style.borderColor="rgba(255,140,0,0.11)";e.currentTarget.style.color="#0F172A";}}>
                <div style={{fontSize:16,marginBottom:3}}>{ico}</div>{lbl}
              </div>
            ))}
            {typeof navigator !== "undefined" && navigator.share && (
              <div onClick={handleNativeShare}
                style={{padding:"9px 8px",borderRadius:10,border:"1.5px solid rgba(255,140,0,0.11)",background:"#fff",textAlign:"center",fontSize:11,fontWeight:700,cursor:"pointer",transition:"all 0.2s",color:"#0F172A"}}
                onMouseEnter={e=>{e.currentTarget.style.borderColor="#FF8C00";e.currentTarget.style.color="#FF8C00";}}
                onMouseLeave={e=>{e.currentTarget.style.borderColor="rgba(255,140,0,0.11)";e.currentTarget.style.color="#0F172A";}}>
                <div style={{fontSize:16,marginBottom:3}}>📤</div>Share…
              </div>
            )}
          </div>
        </div>

        {/* ─── BOOK TICKETS ─── */}
        <div style={{...S.gc(360),gridColumn:"1/4"}}>
          <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:16}}>
            <div style={{display:"flex",alignItems:"center",gap:16}}>
              <div style={{width:56,height:56,borderRadius:16,background:"linear-gradient(135deg,#FF8C00,#FF4500)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:26,boxShadow:"0 8px 28px rgba(255,140,0,0.35)"}}>🎫</div>
              <div>
                <div style={{fontSize:18,fontWeight:800,letterSpacing:"-0.025em"}}>Book Your Tickets</div>
                <div style={{fontSize:13,color:"#475569",marginTop:3}}>
                  {AIRLINES[selAirline].name} · {allStops.map(s=>s.code).join(" → ")} · {totalPax} passenger{totalPax!==1?"s":""}
                </div>
              </div>
            </div>
            <div style={{display:"flex",alignItems:"center",gap:16}}>
              <div style={{textAlign:"right"}}>
                <div style={{fontSize:11,color:"#94A3B8",fontWeight:600}}>Total Estimated Price</div>
                <div style={{fontSize:28,fontWeight:800,color:"#FF8C00",letterSpacing:"-0.03em"}}>{fm(totalCostUSD)}</div>
              </div>
              <button onClick={()=>setShowBooking(true)}
                style={{padding:"14px 32px",borderRadius:14,border:"none",background:"linear-gradient(135deg,#FF8C00,#FF4500)",color:"#fff",fontSize:15,fontWeight:800,cursor:"pointer",boxShadow:"0 8px 30px rgba(255,140,0,0.4)",fontFamily:"inherit",letterSpacing:"-0.01em",transition:"all 0.2s",whiteSpace:"nowrap"}}
                onMouseEnter={e=>e.currentTarget.style.transform="scale(1.03)"}
                onMouseLeave={e=>e.currentTarget.style.transform="scale(1)"}>
                🎫 Book Now
              </button>
            </div>
          </div>
          <div style={{display:"flex",gap:12,marginTop:16,flexWrap:"wrap"}}>
            {[["✅","Free cancellation up to 24h"],["🛡️","Travel insurance included"],["💳","Secure payment"],["📧","Instant e-ticket"]].map(([ico,lbl])=>(
              <div key={lbl} style={{display:"flex",alignItems:"center",gap:6,fontSize:11.5,color:"#475569",background:"rgba(34,197,94,0.06)",border:"1px solid rgba(34,197,94,0.12)",padding:"6px 12px",borderRadius:8}}>
                <span>{ico}</span>{lbl}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Booking Modal */}
      <BookingModal
        show={showBooking}
        onClose={()=>setShowBooking(false)}
        allStops={allStops}
        legs={legs}
        dateStart={dateStart}
        dateEnd={dateEnd}
        nights={nights}
        passengers={passengers}
        payingPax={payingPax}
        totalPax={totalPax}
        totalCostUSD={totalCostUSD}
        fm={fm}
        selAirline={AIRLINES[selAirline]}
        showToast={showToast}
      />
    </div>
  );
}
